# Dependabot configuration for Ready4Hire
# Automatically checks for dependency updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/Ready4Hire"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "ready4hire-team"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/WebApp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "ready4hire-team"
    labels:
      - "dependencies"
      - "dotnet"
    commit-message:
      prefix: "chore"
      include: "scope"

  # React Native dependencies
  - package-ecosystem: "npm"
    directory: "/MobileApp"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    reviewers:
      - "ready4hire-team"
    labels:
      - "dependencies"
      - "mobile"
    commit-message:
      prefix: "chore"
      include: "scope"

  # E2E Tests dependencies
  - package-ecosystem: "npm"
    directory: "/e2e-tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "testing"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci-cd"

